### ISSUE TITLE
[FIXED] Несовместимость с Firefox 63

### ISSUE THREAD

**Issue by sergeevabc** [gromnitsky/easycache#2]
Расширение не работает с текущим релизом Firefox (63.0.3 x64):
- нажатие на иконку ничего не показывает
- настройки пустуют

**Comment by gromnitsky** [comment]
can you check this ver http://gromnitsky.users.sourceforge.net/js/chrome/easycache-1.0.1-fx.xpi via removing the existing easycache installation & DnD'ing the .xpi into `about:addons` page?

(the file is signed by AMO (addons.mozilla.org) but not yet listed in the store)

**Comment by sergeevabc** [comment]
Заработало, спасибо. Правда, поведение курсора неожиданное: думал, после клика по иконке появится окно, выберу архив, откроется таб с архивной версией страницы, а всплывающее окно погаснет, на деле — окошко висит, пока не кликнешь где-то за его пределами.

**Comment by gromnitsky** [comment]
that's an unfortunate peculiarity of ff. in chrome, the same piece of code works exactly as you anticipated it

addons.mozilla.org contains 1.1.0 w/ some bugs fixed--you may delete the test ver & install the new one from the store
